SpringBoot project setup
wolox-training/gf-java pull request #1
Opened 2020-11-04 22:41 UTC by GabyCliff

## Summary
- Completed the project setup
- Finished PR structure
## Trello Card
https://trello.com/c/D6lXPJnc/42-pull-request

2020-11-05 16:56 UTC, Jimenarosello requested changes
The **.idea** and **.gradle** folders should be ignored in the gitignore file. Keep only the gradle wrapper, gradlew and gradlew.bat, so the project can be downloaded and ran by anyone without the need to configure/install gradle 😄

2020-11-09 18:12 UTC, Jimenarosello requested changes
One last thing, remember to remove the files and folders that were uploaded before updating the gitignore file 👼  (.gradle/, .idea/, build/)

2020-11-09 18:12 UTC, Jimenarosello commented on .gitignore
> +build/tmp/compileJava/source-classes-mapping.txt
You can ignore the whole folder with `build/` :)

2020-11-10 20:56 UTC, rabinovichm approved these changes

2020-11-11 18:01 UTC, Jimenarosello approved these changes

2020-11-19 22:49 UTC, merged