Created package controllers with BookController, and added views
wolox-training/gf-java pull request #2
Opened 2020-11-05 16:13 UTC by GabyCliff

## Summary
- Created package controllers
- Created BookController
- Created views named greeting.html
## Trello Card
https://trello.com/c/Pa3dE5ep/17-crear-un-controller-y-una-vista-de-bienvenida

2020-11-05 16:58 UTC, Jimenarosello requested changes
Nice job! Just one comment :) And remember to add .gradle to the gitignore file 😄

2020-11-05 16:58 UTC, Jimenarosello commented on src/main/resources/templates/greeting.html
> +</html>
This file seems to be a duplicate of `build/resources/main/templates/greeting.html`. Which one are you using?

2020-11-09 18:14 UTC, Jimenarosello commented on src/main/resources/templates/greeting.html
> +</html>
Remember to delete the duplicated class :)

2020-11-10 21:09 UTC, rabinovichm approved these changes

2020-11-11 18:01 UTC, Jimenarosello approved these changes
Nice work 😊

2020-11-19 22:48 UTC, merged